version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      SERVER_NAME: "Test SERVER_NAME"
      MOTD: "Test"
      EULA: "true"
      ONLINE_MODE: "false" # Enable online mode
      DIFFICULTY: "hard" # Set the difficulty level (possible values: peaceful, easy, normal, hard)
      MEMORY: "800M" # Allocate 2GB of memory to the Minecraft server
      VERSION: "1.20.1"
    volumes:
      - /path/to/minecraft_data:/data
